eRecruiter/eRecruiter.Api

- ChangeLog.md
- eRecruiter.Api/Parameters/Applicant/ApplicantParameter.cs
- eRecruiter.Api/Parameters/CvParserParameter.cs
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/CvParserResponse.cs
- eRecruiter.Api/Responses/Mandator/PortalSettingsResponse.cs
Add new portal setting "EnableCvParsing".
> 6 portalsetting for cvparsing

- ChangeLog.md
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Job/JobPublicationResponse.cs
- eRecruiter.Api/Responses/Job/JobResponse.cs
Integration of multi-posting configuration properties for job publication channels. This can be used to provide a better feed for multi-posting solutions that consume the job ads.
> #10 multiposting partner support

- .gitignore
- ChangeLog.md
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/CustomField/CustomFieldResponse.cs
added HTML custom field support to API specification
> #14 html custom field support

- ChangeLog.md
- eRecruiter.Api/Parameters/Applicant/ApplicantParameter.cs
- eRecruiter.Api/Parameters/CvParserParameter.cs
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/CvParserResponse.cs
- eRecruiter.Api/Responses/Mandator/PortalSettingsResponse.cs
> #16 extended date selection portal setting

- ChangeLog.md
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Mandator/MandatorResponse.cs
* added property for occupation type
> #28 occupation type settings

- ChangeLog.md
- eRecruiter.Api.Client/ApiHttpClient.cs
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/Requests/Synchronize/CompanySynchronizeRequest.cs
- eRecruiter.Api.CommandLineClient/CommandlineOptions.cs
- eRecruiter.Api.CommandLineClient/CompanySynchronizeRequest.cs
- eRecruiter.Api.CommandLineClient/Program.cs
- eRecruiter.Api.CommandLineClient/Properties/AssemblyInfo.cs
- eRecruiter.Api/Parameters/Synchronize/CompanySynchronizeParameter.cs
- eRecruiter.Api/Responses/Synchronize/CompanySynchronizeResponse.cs
- eRecruiter.Api/Responses/Synchronize/Message.cs
- eRecruiter.Api/Responses/Synchronize/SyncResult.cs
Apply new paramter, fix typo and increase Versions plus dependencies
> #39 add company import   add url parameter 

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/Requests/Application/ApplicationsByReferrerRequests.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.csproj
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api.CommandLineClient/ApplicantByGlobalIdRequests.cs
- eRecruiter.Api.CommandLineClient/CommandlineOptions.cs
- eRecruiter.Api.CommandLineClient/Program.cs
- eRecruiter.Api.CommandLineClient/Properties/AssemblyInfo.cs
- eRecruiter.Api.CommandLineClient/ReferrerRequests.cs
- eRecruiter.Api.CommandLineClient/eRecruiter.Api.CommandLineClient.csproj
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Application/ApplicationReferrerResponse.cs
- eRecruiter.Api/WorkflowStatusGroup.cs
- eRecruiter.Api/eRecruiter.Api.csproj
Changes:
* added response object for applications by referrer requests
* added enumeration for workflow status groups
* added request for applications by referrer
* added logic to command-line client for testing
> [DEV-1435] added new API call for applications by referrer

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/Requests/Application/ApplicationsByReferrerRequests.cs
- eRecruiter.Api.CommandLineClient/ReferrerRequests.cs
Changes:
* added time range filter for applications by referrer
> [DEV-1435] added time range filter for applications by referrer

- ChangeLog.md
- eRecruiter.Api.sln
- eRecruiter.Api/Parameters/CustomField/CustomFieldValueParameter.cs
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/CustomField/CustomFieldResponse.cs
- eRecruiter.Api/Responses/CustomField/CustomFieldValueResponse.cs
- eRecruiter.Api/Responses/Job/JobResponse.cs
Add custom fields documentation to avoid further misunderstandings.
> Customfield docs

- ChangeLog.md
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Mandator/PortalSettingsResponse.cs
Added new portal settings for jobs list pagination
> [PDE-114] applicant portal pagination

- ChangeLog.md
- eRecruiter.Api/HistoryType.cs
- eRecruiter.Api/Properties/AssemblyInfo.cs
- Created new type for HistoryType to support privacy policies updates
> [PDE-133] privacy policy history type

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/Requests/Applicant/ApplicantPoliciesRequests.cs
- eRecruiter.Api.Client/Requests/Applicant/ApplicantPolicyRequests.cs
- eRecruiter.Api.Client/Requests/Policies/PoliciesRequests.cs
- eRecruiter.Api.Client/Requests/Policies/PolicyRequests.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.csproj
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Parameters/Applicant/ApplicantPolicyParameter.cs
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Applicant/ApplicantPolicyResponse.cs
- eRecruiter.Api/Responses/Policies/PolicyResponse.cs
- eRecruiter.Api/Responses/Policies/PolicyType.cs
- eRecruiter.Api/eRecruiter.Api.csproj
- New API call to retrieve the latest policies
- New API call to request a specific policy
- New API call to request the policies for an applicant
- New API call to update a policy for an applicant
> [PDE-138] api extension for agreements

- ChangeLog.md
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Mandator/PortalSettingsResponse.cs
- Created new property on PortalSettingResponse to handle the visibility of the privacy policy agreement.
> [PDE-142] registration policy agreement

- ChangeLog.md
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Mandator/PortalSettingsResponse.cs
- Changed naming of property which handles the visibility of the policy to be more clear.
> [PDE-165] privacy policy naming

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/Requests/Policies/PoliciesRequests.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
- Added portal and culture parameters to support per portal policies
> Pde 161 per portal policies

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/Requests/Applicant/ApplicantCvRequests.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
- Created new endpoint to get a cv for an applicant in the european format
> [PDE-168] eu cv api extension

- ChangeLog.md
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Mandator/PortalSettingsResponse.cs
- Created new property to enable/disable de european cv in the applicant profile
> [PDE-169] european eu cv

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/Requests/Applicant/ApplicantsRequest.cs
- eRecruiter.Api.Client/Requests/Application/ApplicationsByJobRequests.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.csproj
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Application/ApplicationJobResponse.cs
- eRecruiter.Api/eRecruiter.Api.csproj
[PDE-219] added applicant by custom field search
[PDE-225] added applications by job search
> API Search Extensions

- ChangeLog.md
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Job/GeoLocationResponse.cs
- eRecruiter.Api/Responses/Job/JobGeoLocationResponse.cs
- eRecruiter.Api/Responses/Job/JobResponse.cs
- eRecruiter.Api/eRecruiter.Api.csproj
- Created new property `Geolocation` of type `JobGeoLocationResponse` in JobResponse  which contains information about the job geolocation.
> [PDE-198] job api geographic information

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Mandator/PortalSettingsResponse.cs
The legacy XING settings have been removed in favor of _Login with XING_.
> [PDE-222] Legacy XING Integration Removal

- ChangeLog.md
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Mandator/PortalSettingsResponse.cs
- Added legacy properties XingConsumerKey and XingConsumerSecret
> [PDE-235] api legacy properties

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Mandator/PortalSettingsResponse.cs
- Removed legacy XING api settings
> [PDE-236] legacy xing settings

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Job/JobResponse.cs
> [PDE-274] api job ad block titles

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Job/JobResponse.cs
- Added geo location name in JobResponse
> [PDE-277] api job ad location

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Job/JobResponse.cs
- eRecruiter.Api/Responses/Job/JobsResponse.cs
-Changed ChannelSettings from JobsResponse to JobResponse
> [PDE-281] api job ad channel settings

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Mandator/QuestionnaireItemResponse.cs
- Created
- Add ApplicantDocument to QuestionnaireItemType
> [PDE 290] - Applicant Portal Questionnaire Document

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/Requests/Job/JobRequest.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Parameters/Job/CustomField.cs
- eRecruiter.Api/Parameters/Job/JobParameter.cs
- eRecruiter.Api/Parameters/Job/JobStatus.cs
- eRecruiter.Api/Parameters/Job/JobText.cs
- eRecruiter.Api/Parameters/Job/SocialMedia.cs
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Job/JobCreationResponse.cs
- eRecruiter.Api/eRecruiter.Api.csproj
- Created endpoint for new jobs
- Created new job parameter
- Created new job creation response
> [PDE-296] api job creation

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Parameters/Job/CustomFieldParameter.cs
- eRecruiter.Api/Parameters/Job/JobParameter.cs
- eRecruiter.Api/Parameters/Job/JobTextParameter.cs
- eRecruiter.Api/Parameters/Job/SocialMediaParameter.cs
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/eRecruiter.Api.csproj
- Changed classes names to avoid ambiguity on api.server
- Changed culture to string
> Pde 296 api job creation

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Account/ApplicantSetPasswordResponse.cs
- eRecruiter.Api/Responses/Account/ValidatePasswordResponse.cs
[PDE-384](https://jira.erecruiter.net/browse/PDE-384)
-Update password responses to match eRecruiter requirements
> [PDE-384] Update password responses to match eRecruiter requirements

- ChangeLog.md
-ChangeLog updated to have a better description
> -update ChangeLog

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Job/JobResponse.cs
> [DOD-3735] missing employment mapping

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Mandator/PortalSettingsResponse.cs
-Update PortalSettingsResponse to support karriere.at one-click widget
[Task link](https://erwin.atlassian.net/browse/PDE-637)
> PDE-637 One-click-widget integration 

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Job/GoogleForJobsLocationResponse.cs
- eRecruiter.Api/Responses/Job/GoogleForJobsResponse.cs
- eRecruiter.Api/Responses/Job/JobResponse.cs
- eRecruiter.Api/eRecruiter.Api.csproj
- Added GoogleForJobsResponse to JobResponse
- Added GoogleForJobsLocationResponse
- Added GoogleForJobsLocationResponse list to GoogleForJobsResponse
> [PDE-617] g4j api extension

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Job/GoogleForJobsResponse.cs
- Changed `GoogleForJobsResponse` MinSalary and MaxSalary to double nullable types.
> Pde 617 g4j api extension

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/Requests/Integrations/ApplyWithRequest.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Integrations/ApplyWithSettingResponse.cs
- eRecruiter.Api/eRecruiter.Api.csproj
- Added new endpoint to fetch "Apply With eRecruiter" setting based on clientId.
- `ApplyWithSettingResponse` has been added to support this new endpoint.
> [PDE-790] heyjobs-apply-with-erecruiter-setting-api

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Integrations/ApplyWithSettingResponse.cs
- Changed `Values` field of `ApplyWithSettingCustomFieldResponse` class to a Collection of strings.
> [PDE-830] heyjobs-apply-with-erecruiter-cover-letter

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Integrations/ApplyWithSettingResponse.cs
- Add `CoverLetter` to `ApplyWithSettingFieldsResponse`.
> [PDE-830] heyjobs apply with erecruiter cover letter

- ChangeLog.md
- eRecruiter.Api.Client/Properties/AssemblyInfo.cs
- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
- eRecruiter.Api/Responses/Integrations/ApplyWithSettingResponse.cs
- Add `Url` to `ApplyWithSettingPolicyResponse`
> [PDE-830] apply-with-settings-privacy-policy-links

- ChangeLog.md
- eRecruiter.Api/Responses/Mandator/MandatorResponse.cs
[PDE-2822] - Added new property for mandator VideoRecruitingProvider
[PDE-2822]: https://erwin.atlassian.net/browse/PDE-2822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PDE-2822] - Added new property for mandator VideoRecruitingProvider

- eRecruiter.Api.Client/eRecruiter.Api.Client.nuspec
- eRecruiter.Api/Properties/AssemblyInfo.cs
[PDE-2822] Update version
[PDE-2822]: https://erwin.atlassian.net/browse/PDE-2822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PDE-2822] Update version
